### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by spifftek70** [tyrasd/togpx#4]
okay, figured out that issue... by...   why does togpx cycle through twice and null the lat/long's on the 2nd iteration?

    $("#exportGPX").on('click', function (event) {
                GPXfile = '';
                raw = response.route.shape.shapePoints;
                var string = JSON.stringify(raw);
                var matches = string.replace(/([-\d.]+),([-\d.]+)/g, ' [$2,$1] ');
                var newMatch = JSON.parse(matches);
                var selectedGeojson = {"type": "FeatureCollection", "features": [
                        {"type": "Feature",
                            "properties": {
                                "name": "Route",
                                "popupContent": "Your Route"},
                            "geometry": {"type": "LineString", "coordinates": newMatch}}]};
                GPXfile = togpx(selectedGeojson);
                data = 'data:application/octet-stream,' + encodeURIComponent(PGXis);
                location.href = data;
            });

**Comment by tyrasd** [comment]
I don't really get the problem here. Where does togpx null any coordinates?

**Comment by spifftek70** [comment]
It gets to the end of that function and cycles back through it.  I created an error to force it out of the 2nd loop.

**Comment by tyrasd** [comment]
As far as I can see, this doesn't have anything to do with the togpx library. Maybe some other part in you code is causing the duplicate event-triggering? (for example if you had bound the event handler twice to the DOM element)
