### ISSUE TITLE
Update jxon dependency version

### ISSUE THREAD

**Issue by boblauer** [tyrasd/togpx#7]
`jxon@1.0.0` erroneously defines `global.document` in node, which can break other libraries that try to detect if they're running in the browser by checking the existence of `global.document`.

This bug has been fixed in `jxon@latest`.  Any chance you could upgrade your dependency on `jxon` to `@latest`?

**Comment by tyrasd** [comment]
right. this took a bit longer than expected, because in jxon 1.x there were some issues with xmlns, that are now finally fixed with jxon 2.0.0(-beta).

I'll tag an npm release of togpx once jxon gets a proper 2.0.0 release.
